
services:
  postgres:
    image: postgres:latest
    container_name: mi_postgres
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: lauchilus
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
